#!/usr/bin/env node

require("./lib/qxcli");

// main config
var title = "qooxdoo command line interface";
title = "\n" + title + "\n" + "=".repeat(title.length) + "\n";
title += `Versions: qooxdoo-cli v${qxcli.Version.VERSION}, qooxdoo-compiler v${qxcompiler.Version.VERSION}\n\n`;
title +=
`Typical usage:
  qx <commands> [options]
  
Type qx <command> --help for options and subcommands.`

require('yargs')
  .locale("en")
  .commandDir('commands')
  .usage(title)
  .demandCommand()
  .strict()
  .showHelpOnFail()
  .argv;